## 오류처리 (Error Handling)
- 프로그램이 오류를 일으켰을 때 감지하고 회복시키는 일련의 과정
- 스위프트의 오류처리를 통해 시스템의 오류를 처리할 수 있는 건 아님

## `Error` 프로토콜
- 스위프트에서 오류는 `Error`라는 프로토콜을 준수하는 타입의 값을 통해 표현
    - Error 프로토콜은 사실상 요구사항이 없는 빈 프로토콜일 뿐이지만 오류를 표현하기 위한 타입(주로 열거형)은 이 프로토콜을 채택
- 스위프트의 열거형은 오류의 종류를 나타내기에 아주 적합한 기능
- 연관 값을 통해 오류에 관한 부가 정보를 제공할 수도 있음
- 오류를 던져줄 때는 `throw` 구문을 사용

## 오류처리 방법
- 스위프트는 오류를 처리하기 위한 네 가지 방법이 있음
  1. **함수에서 발생한 오류를 해당 함수를 호출한 코드에 알리는 방법**
  2. **do-catch 구문을 이용하여 오류를 처리하는 방법**
  3. **옵셔널 값으로 오류를 처리하는 방법**
  4. **오류가 발생하지 않을 것이라고 확신하는 방법**

### 함수에서 발생한 오류 알리기
- **try** 키워드로 던져진 오류를 받을 수 있음
    - **try** 또는 **try?**, **try!** 등으로 표현할 수 있음

### do-catch 구문을 이용하여 오류처리
- `catch` 키워드 뒤에 처리할 오류의 종류를 작성
- 여러개의 오류도 하나의 `catch` 절에서 매칭 가능
- `catch` 뒤에 오류의 종류를 명시하지 않고 코드 블록을 생성하면 블록 내부에 암시적으로 `error`라는 이름의 지역 상수가 오류의 내용으로 들어옴

### 옵셔널 값으로 오류처리
- `try?` 표현을 통해 동작하던 코드가 오류를 던지면 그 코드의 반환 값은 nil이 됨

### 오류가 발생하지 않을 것이라고 확신하는 방법
- `try!` 표현을 통해 실제 오류가 발생하면 런타임 오류가 발생하여 프로그램이 강제로 종료됨

### 다시 던지기 (Rethrowning)
- 함수나 메서드는 `rethrows` 키워드를 사용해 자신의 매개변수로 전달받은 함수가 오류를 던진다는 것을 나타낼 수 있음
- 다시 던지기를 가능하게 하려면 최소 하나 이상의 오류 발생 가능한 함수를 매개변수로 전달받아야 함

#### 다시 던지기의 특징
- 다시 던지기 함수 또는 메서드는 기본적으로 스스로 오류를 던지지 못하므로 자신 내부에 직접적으로 `throw` 구문을 사용할 수 없음
- 그러나 `catch` 절 내부에서는 `throw` 구문을 작성할 수 있음
- 다시 던지기 함수나 메서드가 오류를 던지는 함수를 **do-catch** 구문 내부에서 호출하고 **catch** 절 내부에서 다른 오류를 던짐으로써 오류를 던지는 함수에서 발생한 오류를 제어할 수 있음

## 후처리
- `defer` 구문을 사용해 현재 코드 블록을 나가기 전에 꼭 실행해야 하는 코드를 작성해줄 수 있음
- `defer` 구문 내부에는 `break`, `return` 등과 같이 구문을 빠져나갈 수 있는 코드 또는 오류를 던지는 코드는 작성하면 안 됨
- 여러 개의 `defer` 구문이 하나의 범위(블록) 내부에 속해 있다면 맨 마지막에 작성된 구문부터 역순으로 실행

## 오류 타입 지정하기
- 어떤 타입의 오류를 던지고 받을지 명확히 명시하고 싶을 때 `throws (any Error)`와 같이 괄호를 열고 던지는 타입을 명시
